apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: juice-shop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: juice-shop
        tier: frontend
    spec:
      containers:
        - name: juice-shop
          image: bkimminich/juice-shop
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: juice-shop-frontend
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: juice-shop-frontend
    tier: frontend
spec:
  type: LoadBalancer
  loadBalancerIP: 10.5.2.5
  ports:
    - port: 80
  selector:
    app: juice-shop
    tier: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: juice-shop
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: juice-shop
  #type: NodePort